triggers:
   - name: trisample1
     type: trigger
     version:
       counter: 80
   - name: trisample2
     type: trigger
     version:
      #message: 'new teswt2'
       counter: 2
      
  #- name: triggertest3
   # type: trigger
  #  source:
   #   message: 'tewwt3'
    #  counter: 3
